apiVersion: v1
kind: Service

metadata:
  name: app-scanner
  namespace: scanner
  labels:
    app: frontend

spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5050

  selector:
    app: frontend

  type: LoadBalancer
